/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FirewallCreateIngress'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FirewallCreateIngress'));
  } else {
    // Browser globals (root is window)
    if (!root.HyperoneClient) {
      root.HyperoneClient = {};
    }
    root.HyperoneClient.FirewallUpdate = factory(root.HyperoneClient.ApiClient, root.HyperoneClient.FirewallCreateIngress);
  }
}(this, function(ApiClient, FirewallCreateIngress) {
  'use strict';



  /**
   * The FirewallUpdate model module.
   * @module model/FirewallUpdate
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>FirewallUpdate</code>.
   * @alias module:model/FirewallUpdate
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>FirewallUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FirewallUpdate} obj Optional instance to populate.
   * @return {module:model/FirewallUpdate} The populated <code>FirewallUpdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('ingress')) {
        obj['ingress'] = ApiClient.convertToType(data['ingress'], [FirewallCreateIngress]);
      }
      if (data.hasOwnProperty('egress')) {
        obj['egress'] = ApiClient.convertToType(data['egress'], [FirewallCreateIngress]);
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Array.<module:model/FirewallCreateIngress>} ingress
   */
  exports.prototype['ingress'] = undefined;
  /**
   * @member {Array.<module:model/FirewallCreateIngress>} egress
   */
  exports.prototype['egress'] = undefined;



  return exports;
}));


