/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageAttachedOn', 'model/ImageDisk'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageAttachedOn'), require('./ImageDisk'));
  } else {
    // Browser globals (root is window)
    if (!root.HyperoneClient) {
      root.HyperoneClient = {};
    }
    root.HyperoneClient.ImageDisks = factory(root.HyperoneClient.ApiClient, root.HyperoneClient.ImageAttachedOn, root.HyperoneClient.ImageDisk);
  }
}(this, function(ApiClient, ImageAttachedOn, ImageDisk) {
  'use strict';



  /**
   * The ImageDisks model module.
   * @module model/ImageDisks
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>ImageDisks</code>.
   * @alias module:model/ImageDisks
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ImageDisks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageDisks} obj Optional instance to populate.
   * @return {module:model/ImageDisks} The populated <code>ImageDisks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('size')) {
        obj['size'] = ApiClient.convertToType(data['size'], 'Number');
      }
      if (data.hasOwnProperty('fileSize')) {
        obj['fileSize'] = ApiClient.convertToType(data['fileSize'], 'Number');
      }
      if (data.hasOwnProperty('attachedOn')) {
        obj['attachedOn'] = ImageAttachedOn.constructFromObject(data['attachedOn']);
      }
      if (data.hasOwnProperty('disk')) {
        obj['disk'] = ImageDisk.constructFromObject(data['disk']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ImageDisks.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} size
   */
  exports.prototype['size'] = undefined;
  /**
   * @member {Number} fileSize
   */
  exports.prototype['fileSize'] = undefined;
  /**
   * @member {module:model/ImageAttachedOn} attachedOn
   */
  exports.prototype['attachedOn'] = undefined;
  /**
   * @member {module:model/ImageDisk} disk
   */
  exports.prototype['disk'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "archive"
     * @const
     */
    "archive": "archive",
    /**
     * value: "volume"
     * @const
     */
    "volume": "volume",
    /**
     * value: "ssd"
     * @const
     */
    "ssd": "ssd",
    /**
     * value: "hissd"
     * @const
     */
    "hissd": "hissd",
    /**
     * value: "ephemeral-hissd"
     * @const
     */
    "ephemeral-hissd": "ephemeral-hissd",
    /**
     * value: "replica"
     * @const
     */
    "replica": "replica"  };


  return exports;
}));


