/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ImageActionTransfer model module.
 * @module model/ImageActionTransfer
 * @version 0.0.3
 */
class ImageActionTransfer {
    /**
     * Constructs a new <code>ImageActionTransfer</code>.
     * @alias module:model/ImageActionTransfer
     * @param project {String} 
     */
    constructor(project) { 
        
        ImageActionTransfer.initialize(this, project);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, project) { 
        obj['project'] = project;
    }

    /**
     * Constructs a <code>ImageActionTransfer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImageActionTransfer} obj Optional instance to populate.
     * @return {module:model/ImageActionTransfer} The populated <code>ImageActionTransfer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImageActionTransfer();

            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} project
 */
ImageActionTransfer.prototype['project'] = undefined;






export default ImageActionTransfer;

