/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrganisationUpdateBilling'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrganisationUpdateBilling'));
  } else {
    // Browser globals (root is window)
    if (!root.HyperoneClient) {
      root.HyperoneClient = {};
    }
    root.HyperoneClient.OrganisationUpdate = factory(root.HyperoneClient.ApiClient, root.HyperoneClient.OrganisationUpdateBilling);
  }
}(this, function(ApiClient, OrganisationUpdateBilling) {
  'use strict';



  /**
   * The OrganisationUpdate model module.
   * @module model/OrganisationUpdate
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>OrganisationUpdate</code>.
   * @alias module:model/OrganisationUpdate
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>OrganisationUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrganisationUpdate} obj Optional instance to populate.
   * @return {module:model/OrganisationUpdate} The populated <code>OrganisationUpdate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('billing')) {
        obj['billing'] = OrganisationUpdateBilling.constructFromObject(data['billing']);
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/OrganisationUpdateBilling} billing
   */
  exports.prototype['billing'] = undefined;



  return exports;
}));


