/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceBillingPrice model module.
 * @module model/ServiceBillingPrice
 * @version 0.0.3
 */
class ServiceBillingPrice {
    /**
     * Constructs a new <code>ServiceBillingPrice</code>.
     * @alias module:model/ServiceBillingPrice
     */
    constructor() { 
        
        ServiceBillingPrice.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceBillingPrice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceBillingPrice} obj Optional instance to populate.
     * @return {module:model/ServiceBillingPrice} The populated <code>ServiceBillingPrice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceBillingPrice();

            if (data.hasOwnProperty('PLN')) {
                obj['PLN'] = ApiClient.convertToType(data['PLN'], 'Number');
            }
            if (data.hasOwnProperty('EUR')) {
                obj['EUR'] = ApiClient.convertToType(data['EUR'], 'Number');
            }
            if (data.hasOwnProperty('USD')) {
                obj['USD'] = ApiClient.convertToType(data['USD'], 'Number');
            }
            if (data.hasOwnProperty('GBP')) {
                obj['GBP'] = ApiClient.convertToType(data['GBP'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} PLN
 */
ServiceBillingPrice.prototype['PLN'] = undefined;

/**
 * @member {Number} EUR
 */
ServiceBillingPrice.prototype['EUR'] = undefined;

/**
 * @member {Number} USD
 */
ServiceBillingPrice.prototype['USD'] = undefined;

/**
 * @member {Number} GBP
 */
ServiceBillingPrice.prototype['GBP'] = undefined;






export default ServiceBillingPrice;

