/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserCredentialPassword'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserCredentialPassword'));
  } else {
    // Browser globals (root is window)
    if (!root.HyperOneApi) {
      root.HyperOneApi = {};
    }
    root.HyperOneApi.UserCredential = factory(root.HyperOneApi.ApiClient, root.HyperOneApi.UserCredentialPassword);
  }
}(this, function(ApiClient, UserCredentialPassword) {
  'use strict';



  /**
   * The UserCredential model module.
   * @module model/UserCredential
   * @version 0.0.2
   */

  /**
   * Constructs a new <code>UserCredential</code>.
   * @alias module:model/UserCredential
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>UserCredential</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserCredential} obj Optional instance to populate.
   * @return {module:model/UserCredential} The populated <code>UserCredential</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('password')) {
        obj['password'] = UserCredentialPassword.constructFromObject(data['password']);
      }
      if (data.hasOwnProperty('certificate')) {
        obj['certificate'] = UserCredentialPassword.constructFromObject(data['certificate']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/UserCredentialPassword} password
   */
  exports.prototype['password'] = undefined;
  /**
   * @member {module:model/UserCredentialPassword} certificate
   */
  exports.prototype['certificate'] = undefined;



  return exports;
}));


