/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VmPostHdd model module.
 * @module model/VmPostHdd
 * @version 0.0.3
 */
class VmPostHdd {
    /**
     * Constructs a new <code>VmPostHdd</code>.
     * @alias module:model/VmPostHdd
     * @param disk {String} 
     */
    constructor(disk) { 
        
        VmPostHdd.initialize(this, disk);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, disk) { 
        obj['disk'] = disk;
    }

    /**
     * Constructs a <code>VmPostHdd</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VmPostHdd} obj Optional instance to populate.
     * @return {module:model/VmPostHdd} The populated <code>VmPostHdd</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VmPostHdd();

            if (data.hasOwnProperty('disk')) {
                obj['disk'] = ApiClient.convertToType(data['disk'], 'String');
            }
            if (data.hasOwnProperty('controllerType')) {
                obj['controllerType'] = ApiClient.convertToType(data['controllerType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} disk
 */
VmPostHdd.prototype['disk'] = undefined;

/**
 * @member {String} controllerType
 */
VmPostHdd.prototype['controllerType'] = undefined;






export default VmPostHdd;

