/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VmUpdate model module.
 * @module model/VmUpdate
 * @version 0.0.3
 */
class VmUpdate {
    /**
     * Constructs a new <code>VmUpdate</code>.
     * @alias module:model/VmUpdate
     */
    constructor() { 
        
        VmUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VmUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VmUpdate} obj Optional instance to populate.
     * @return {module:model/VmUpdate} The populated <code>VmUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VmUpdate();

            if (data.hasOwnProperty('userMetadata')) {
                obj['userMetadata'] = ApiClient.convertToType(data['userMetadata'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} userMetadata
 */
VmUpdate.prototype['userMetadata'] = undefined;

/**
 * @member {String} name
 */
VmUpdate.prototype['name'] = undefined;






export default VmUpdate;

