/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.2
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Event', 'model/Vmhost', 'model/VmhostActionMoveDisk', 'model/VmhostActionMoveISO', 'model/VmhostActionMoveImage', 'model/VmhostActionMoveVM', 'model/VmhostPostAccessrights', 'model/VmhostServices', 'model/VmhostUpdate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Event'), require('../model/Vmhost'), require('../model/VmhostActionMoveDisk'), require('../model/VmhostActionMoveISO'), require('../model/VmhostActionMoveImage'), require('../model/VmhostActionMoveVM'), require('../model/VmhostPostAccessrights'), require('../model/VmhostServices'), require('../model/VmhostUpdate'));
  } else {
    // Browser globals (root is window)
    if (!root.HyperOneApi) {
      root.HyperOneApi = {};
    }
    root.HyperOneApi.VmhostApi = factory(root.HyperOneApi.ApiClient, root.HyperOneApi.Event, root.HyperOneApi.Vmhost, root.HyperOneApi.VmhostActionMoveDisk, root.HyperOneApi.VmhostActionMoveISO, root.HyperOneApi.VmhostActionMoveImage, root.HyperOneApi.VmhostActionMoveVM, root.HyperOneApi.VmhostPostAccessrights, root.HyperOneApi.VmhostServices, root.HyperOneApi.VmhostUpdate);
  }
}(this, function(ApiClient, Event, Vmhost, VmhostActionMoveDisk, VmhostActionMoveISO, VmhostActionMoveImage, VmhostActionMoveVM, VmhostPostAccessrights, VmhostServices, VmhostUpdate) {
  'use strict';

  /**
   * Vmhost service.
   * @module api/VmhostApi
   * @version 0.0.2
   */

  /**
   * Constructs a new VmhostApi. 
   * @alias module:api/VmhostApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * /actions/moveDisk
     * Action moveDisk
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostActionMoveDisk} vmhostActionMoveDisk 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Vmhost} and HTTP response
     */
    this.vmhostActionMoveDiskWithHttpInfo = function(vmhostId, vmhostActionMoveDisk) {
      var postBody = vmhostActionMoveDisk;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostActionMoveDisk");
      }

      // verify the required parameter 'vmhostActionMoveDisk' is set
      if (vmhostActionMoveDisk === undefined || vmhostActionMoveDisk === null) {
        throw new Error("Missing the required parameter 'vmhostActionMoveDisk' when calling vmhostActionMoveDisk");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Vmhost;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/actions/moveDisk', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /actions/moveDisk
     * Action moveDisk
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostActionMoveDisk} vmhostActionMoveDisk 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Vmhost}
     */
    this.vmhostActionMoveDisk = function(vmhostId, vmhostActionMoveDisk) {
      return this.vmhostActionMoveDiskWithHttpInfo(vmhostId, vmhostActionMoveDisk)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /actions/moveISO
     * Action moveISO
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostActionMoveISO} vmhostActionMoveISO 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Vmhost} and HTTP response
     */
    this.vmhostActionMoveISOWithHttpInfo = function(vmhostId, vmhostActionMoveISO) {
      var postBody = vmhostActionMoveISO;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostActionMoveISO");
      }

      // verify the required parameter 'vmhostActionMoveISO' is set
      if (vmhostActionMoveISO === undefined || vmhostActionMoveISO === null) {
        throw new Error("Missing the required parameter 'vmhostActionMoveISO' when calling vmhostActionMoveISO");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Vmhost;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/actions/moveISO', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /actions/moveISO
     * Action moveISO
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostActionMoveISO} vmhostActionMoveISO 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Vmhost}
     */
    this.vmhostActionMoveISO = function(vmhostId, vmhostActionMoveISO) {
      return this.vmhostActionMoveISOWithHttpInfo(vmhostId, vmhostActionMoveISO)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /actions/moveImage
     * Action moveImage
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostActionMoveImage} vmhostActionMoveImage 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Vmhost} and HTTP response
     */
    this.vmhostActionMoveImageWithHttpInfo = function(vmhostId, vmhostActionMoveImage) {
      var postBody = vmhostActionMoveImage;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostActionMoveImage");
      }

      // verify the required parameter 'vmhostActionMoveImage' is set
      if (vmhostActionMoveImage === undefined || vmhostActionMoveImage === null) {
        throw new Error("Missing the required parameter 'vmhostActionMoveImage' when calling vmhostActionMoveImage");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Vmhost;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/actions/moveImage', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /actions/moveImage
     * Action moveImage
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostActionMoveImage} vmhostActionMoveImage 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Vmhost}
     */
    this.vmhostActionMoveImage = function(vmhostId, vmhostActionMoveImage) {
      return this.vmhostActionMoveImageWithHttpInfo(vmhostId, vmhostActionMoveImage)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /actions/moveVM
     * Action moveVM
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostActionMoveVM} vmhostActionMoveVM 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Vmhost} and HTTP response
     */
    this.vmhostActionMoveVMWithHttpInfo = function(vmhostId, vmhostActionMoveVM) {
      var postBody = vmhostActionMoveVM;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostActionMoveVM");
      }

      // verify the required parameter 'vmhostActionMoveVM' is set
      if (vmhostActionMoveVM === undefined || vmhostActionMoveVM === null) {
        throw new Error("Missing the required parameter 'vmhostActionMoveVM' when calling vmhostActionMoveVM");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Vmhost;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/actions/moveVM', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /actions/moveVM
     * Action moveVM
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostActionMoveVM} vmhostActionMoveVM 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Vmhost}
     */
    this.vmhostActionMoveVM = function(vmhostId, vmhostActionMoveVM) {
      return this.vmhostActionMoveVMWithHttpInfo(vmhostId, vmhostActionMoveVM)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.vmhostDeleteWithHttpInfo = function(vmhostId) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostDelete");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.vmhostDelete = function(vmhostId) {
      return this.vmhostDeleteWithHttpInfo(vmhostId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /accessrights/:identity
     * @param {String} vmhostId ID of vmhost
     * @param {String} identity identity
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Vmhost} and HTTP response
     */
    this.vmhostDeleteAccessrightsIdentityWithHttpInfo = function(vmhostId, identity) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostDeleteAccessrightsIdentity");
      }

      // verify the required parameter 'identity' is set
      if (identity === undefined || identity === null) {
        throw new Error("Missing the required parameter 'identity' when calling vmhostDeleteAccessrightsIdentity");
      }


      var pathParams = {
        'vmhostId': vmhostId,
        'identity': identity
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Vmhost;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/accessrights/{identity}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /accessrights/:identity
     * @param {String} vmhostId ID of vmhost
     * @param {String} identity identity
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Vmhost}
     */
    this.vmhostDeleteAccessrightsIdentity = function(vmhostId, identity) {
      return this.vmhostDeleteAccessrightsIdentityWithHttpInfo(vmhostId, identity)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /tag/:key
     * @param {String} vmhostId ID of vmhost
     * @param {String} key key
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    this.vmhostDeleteTagKeyWithHttpInfo = function(vmhostId, key) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostDeleteTagKey");
      }

      // verify the required parameter 'key' is set
      if (key === undefined || key === null) {
        throw new Error("Missing the required parameter 'key' when calling vmhostDeleteTagKey");
      }


      var pathParams = {
        'vmhostId': vmhostId,
        'key': key
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Object;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/tag/{key}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /tag/:key
     * @param {String} vmhostId ID of vmhost
     * @param {String} key key
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    this.vmhostDeleteTagKey = function(vmhostId, key) {
      return this.vmhostDeleteTagKeyWithHttpInfo(vmhostId, key)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /services/:serviceId
     * @param {String} vmhostId ID of vmhost
     * @param {String} serviceId serviceId
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/VmhostServices} and HTTP response
     */
    this.vmhostGetServicesServiceIdWithHttpInfo = function(vmhostId, serviceId) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostGetServicesServiceId");
      }

      // verify the required parameter 'serviceId' is set
      if (serviceId === undefined || serviceId === null) {
        throw new Error("Missing the required parameter 'serviceId' when calling vmhostGetServicesServiceId");
      }


      var pathParams = {
        'vmhostId': vmhostId,
        'serviceId': serviceId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = VmhostServices;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/services/{serviceId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /services/:serviceId
     * @param {String} vmhostId ID of vmhost
     * @param {String} serviceId serviceId
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/VmhostServices}
     */
    this.vmhostGetServicesServiceId = function(vmhostId, serviceId) {
      return this.vmhostGetServicesServiceIdWithHttpInfo(vmhostId, serviceId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /tag
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    this.vmhostGetTagWithHttpInfo = function(vmhostId) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostGetTag");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Object;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/tag', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /tag
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    this.vmhostGetTag = function(vmhostId) {
      return this.vmhostGetTagWithHttpInfo(vmhostId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List
     * List vmhost
     * @param {Object} opts Optional parameters
     * @param {String} opts.enabledServices Filter by enabledServices
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Vmhost>} and HTTP response
     */
    this.vmhostListWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'enabledServices': opts['enabledServices'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Vmhost];
      return this.apiClient.callApi(
        '/vmhost', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List
     * List vmhost
     * @param {Object} opts Optional parameters
     * @param {String} opts.enabledServices Filter by enabledServices
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Vmhost>}
     */
    this.vmhostList = function(opts) {
      return this.vmhostListWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /accessrights
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<String>} and HTTP response
     */
    this.vmhostListAccessrightsWithHttpInfo = function(vmhostId) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostListAccessrights");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ['String'];
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/accessrights', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /accessrights
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<String>}
     */
    this.vmhostListAccessrights = function(vmhostId) {
      return this.vmhostListAccessrightsWithHttpInfo(vmhostId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /queue
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Event>} and HTTP response
     */
    this.vmhostListQueueWithHttpInfo = function(vmhostId) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostListQueue");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Event];
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/queue', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /queue
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Event>}
     */
    this.vmhostListQueue = function(vmhostId) {
      return this.vmhostListQueueWithHttpInfo(vmhostId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /services
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/VmhostServices>} and HTTP response
     */
    this.vmhostListServicesWithHttpInfo = function(vmhostId) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostListServices");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [VmhostServices];
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/services', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /services
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/VmhostServices>}
     */
    this.vmhostListServices = function(vmhostId) {
      return this.vmhostListServicesWithHttpInfo(vmhostId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /tag
     * @param {String} vmhostId ID of vmhost
     * @param {Object.<String, {String: String}>} requestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    this.vmhostPatchTagWithHttpInfo = function(vmhostId, requestBody) {
      var postBody = requestBody;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostPatchTag");
      }

      // verify the required parameter 'requestBody' is set
      if (requestBody === undefined || requestBody === null) {
        throw new Error("Missing the required parameter 'requestBody' when calling vmhostPatchTag");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/tag', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /tag
     * @param {String} vmhostId ID of vmhost
     * @param {Object.<String, {String: String}>} requestBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    this.vmhostPatchTag = function(vmhostId, requestBody) {
      return this.vmhostPatchTagWithHttpInfo(vmhostId, requestBody)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * /accessrights
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostPostAccessrights} vmhostPostAccessrights 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Vmhost} and HTTP response
     */
    this.vmhostPostAccessrightsWithHttpInfo = function(vmhostId, vmhostPostAccessrights) {
      var postBody = vmhostPostAccessrights;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostPostAccessrights");
      }

      // verify the required parameter 'vmhostPostAccessrights' is set
      if (vmhostPostAccessrights === undefined || vmhostPostAccessrights === null) {
        throw new Error("Missing the required parameter 'vmhostPostAccessrights' when calling vmhostPostAccessrights");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Vmhost;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}/accessrights', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * /accessrights
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostPostAccessrights} vmhostPostAccessrights 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Vmhost}
     */
    this.vmhostPostAccessrights = function(vmhostId, vmhostPostAccessrights) {
      return this.vmhostPostAccessrightsWithHttpInfo(vmhostId, vmhostPostAccessrights)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get
     * Returns a single vmhost
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Vmhost} and HTTP response
     */
    this.vmhostShowWithHttpInfo = function(vmhostId) {
      var postBody = null;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostShow");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Vmhost;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get
     * Returns a single vmhost
     * @param {String} vmhostId ID of vmhost
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Vmhost}
     */
    this.vmhostShow = function(vmhostId) {
      return this.vmhostShowWithHttpInfo(vmhostId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update
     * Returns modified vmhost
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostUpdate} vmhostUpdate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Vmhost} and HTTP response
     */
    this.vmhostUpdateWithHttpInfo = function(vmhostId, vmhostUpdate) {
      var postBody = vmhostUpdate;

      // verify the required parameter 'vmhostId' is set
      if (vmhostId === undefined || vmhostId === null) {
        throw new Error("Missing the required parameter 'vmhostId' when calling vmhostUpdate");
      }

      // verify the required parameter 'vmhostUpdate' is set
      if (vmhostUpdate === undefined || vmhostUpdate === null) {
        throw new Error("Missing the required parameter 'vmhostUpdate' when calling vmhostUpdate");
      }


      var pathParams = {
        'vmhostId': vmhostId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Project', 'ServiceAccount', 'Session'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Vmhost;
      return this.apiClient.callApi(
        '/vmhost/{vmhostId}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update
     * Returns modified vmhost
     * @param {String} vmhostId ID of vmhost
     * @param {module:model/VmhostUpdate} vmhostUpdate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Vmhost}
     */
    this.vmhostUpdate = function(vmhostId, vmhostUpdate) {
      return this.vmhostUpdateWithHttpInfo(vmhostId, vmhostUpdate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
