/**
 * HyperOne API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HyperoneClient);
  }
}(this, function(expect, HyperoneClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HyperoneClient.Proforma();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Proforma', function() {
    it('should create an instance of Proforma', function() {
      // uncomment below and update the code to test Proforma
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be.a(HyperoneClient.Proforma);
    });

    it('should have the property additionalInfo (base name: "additionalInfo")', function() {
      // uncomment below and update the code to test the property additionalInfo
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property corrections (base name: "corrections")', function() {
      // uncomment below and update the code to test the property corrections
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property invoiceInfo (base name: "invoiceInfo")', function() {
      // uncomment below and update the code to test the property invoiceInfo
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property invoiceNo (base name: "invoiceNo")', function() {
      // uncomment below and update the code to test the property invoiceNo
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property issueDate (base name: "issueDate")', function() {
      // uncomment below and update the code to test the property issueDate
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property payments (base name: "payments")', function() {
      // uncomment below and update the code to test the property payments
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property seller (base name: "seller")', function() {
      // uncomment below and update the code to test the property seller
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property buyer (base name: "buyer")', function() {
      // uncomment below and update the code to test the property buyer
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property vat (base name: "vat")', function() {
      // uncomment below and update the code to test the property vat
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property summary (base name: "summary")', function() {
      // uncomment below and update the code to test the property summary
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property project (base name: "project")', function() {
      // uncomment below and update the code to test the property project
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property organisation (base name: "organisation")', function() {
      // uncomment below and update the code to test the property organisation
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property duplicate (base name: "duplicate")', function() {
      // uncomment below and update the code to test the property duplicate
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

    it('should have the property _array (base name: "__array__")', function() {
      // uncomment below and update the code to test the property _array
      //var instane = new HyperoneClient.Proforma();
      //expect(instance).to.be();
    });

  });

}));
